name: 🐛 Bug Report
about: 报告 git-helper 中发现的错误或异常行为。

labels:
  - bug
  - needs triage # 标记为需要分类或初步检查

body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间帮助我们改进 git-helper！

        请尽量详细地填写以下信息，以便我们更容易理解和解决问题。

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请清晰地描述您遇到的问题。
      placeholder: 例如：运行选项 9 (同步 Fork) 时，程序崩溃了，并显示了一个错误信息。
      render: markdown
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 重现步骤
      description: 请提供详细的步骤，以便我们重现此问题。
      placeholder: |
        1. 在一个非 Git 仓库目录下运行 git-helper
        2. 选择主菜单选项 1
        3. ...
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 您期望程序在这种情况下如何表现？
      placeholder: 例如：我期望它提示我当前目录不是 Git 仓库，而不是崩溃。
      render: markdown
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: 错误信息和日志 (如果适用)
      description: 请复制并粘贴相关的错误信息、终端输出或日志。请使用代码块 (\`\`\`) 包裹。
      render: markdown

  - type: textarea
    id: screenshots
    attributes:
      label: 截图或录屏 (如果适用)
      description: 提供截图或短视频链接，有助于更直观地展示问题。

  - type: input
    id: os
    attributes:
      label: 操作系统
      placeholder: 例如：Windows 10, macOS Monterey, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python 版本
      placeholder: 例如：Python 3.9.7
    validations:
      required: true

  - type: input
    id: git-version
    attributes:
      label: Git 版本
      placeholder: 例如：git version 2.30.0
    validations:
      required: true

  - type: input
    id: git-helper-version
    attributes:
      label: git-helper 版本或 Commit Hash
      description: 请提供您使用的 git-helper 的版本号或最近的 commit hash (运行 `git rev-parse HEAD` 可以获取)。
      placeholder: 例如：v1.0.0 或 a1b2c3d
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 其他上下文信息
      description: 您认为对理解和解决问题有帮助的任何其他信息，如仓库状态、配置等。
      render: markdown

  - type: checkboxes
    id: confirmation
    attributes:
      label: 确认事项
      description: 请确认您已完成以下事项：
      options:
        - label: 我已搜索了现有的问题，没有发现类似的报告。
          required: true
        - label: 我已阅读并理解了项目的贡献指南 (CONTRIBUTING.md，如果存在的话)。
          required: true